### ISSUE TITLE
[API]タグが無い時にnullがセットされる

### ISSUE THREAD

**Issue by sugarspot** [tamemap-old/tamemap-v2#63]
タグの登録がない場合にJSONにnullがセットされている

空の配列をセットしてください

`{
                                                               "event_id": 8927,
                                                               "title": "?????",
                                                               "price_type": "over1000",
                                                               "enabled": false,
                                                               "freedom_join": false,
                                                               "days": [
                                                                   "2016-12-06",
                                                                   "2016-12-07",
                                                                   "2016-12-12"
                                                               ],
                                                               "time_type": [
                                                                   "evening",
                                                                   "night"
                                                               ],
                                                               "photos": [
                                                                   {
                                                                       "order": 0,
                                                                       "url": "http:\/\/test1.tamemap.net\/tamemapapi\/event_photo\/"
                                                                   },
                                                                   {
                                                                       "order": 1,
                                                                       "url": "http:\/\/test1.tamemap.net\/tamemapapi\/event_photo\/2_1480934237_23154_5845435dc7f18.jpg"
                                                                   },
                                                                   {
                                                                       "order": 2,
                                                                       "url": "http:\/\/test1.tamemap.net\/tamemapapi\/event_photo\/1_1480934237_54213_5845435da35ba.jpg"
                                                                   }
                                                               ],
                                                               "tags": null,
                                                               "place": {
                                                                   "name": "??????",
                                                                   "latitude": "34.3894927",
                                                                   "longitude": "132.4232187",
                                                                   "address": "1 Chome-9-18 K?gokita, Nishi-ku, Hiroshima-shi, Hiroshima-ken 733-0821, Japan"
                                                               },
                                                               "description": "dammy",
                                                               "reservation": true,
                                                               "fcfs": true,
                                                               "url": "http:\/\/test"
                                                           }`

**Comment by sugarspot** [comment]
動作上問題ありわけではないので、優先度は低

**Comment by kota777** [comment]
修正しました
