### ISSUE TITLE
[API]追加した画像のURL補完

### ISSUE THREAD

**Issue by sugarspot** [tamemap-old/tamemap-v2#64]
旧APIの画像アップロードで画像を登録した際に、レスポンスで返却される画像情報がURLではなくファイル名のみになっていました
(旧API：/tamemapapi/upload_photos/)

そのため、eventをPOST,PUTする際にphotoにURLを指定することができません
その際は画像が追加となっているのでurlに指定されているファイル名をeventの画像として追加登録してください

**Comment by kota777** [comment]
> その際は画像が追加となっているのでurlに指定されているファイル名をeventの画像として追加登録してください

つまりurlではなく画像のファイル名のみ送られてくるということでよろしいでしょうか？

**Comment by kota777** [comment]
上記の内容で修正しました。
