### ISSUE TITLE
[Android]ログイン後のアカウントチェック

### ISSUE THREAD

**Issue by sugarspot** [tamemap-old/tamemap-v2#73]
現行のアプリは１回ログインするとログアウトするまで端末に保存しているlogin id(user id)を使用してサーバーにユーザー情報の確認はしていない(Facebookログインも同様）

他端末などからユーザー情報が変更になっても取得する術がない（APIがない）ので、そのあたりを改善した方がよさそう

まずは、対応について検討

**Comment by yoship** [comment]
アカウント削除時にも、、問題になりそうですね、、（by 沖本さん）

起動・復帰時に存在・変更チェック、、でしょうか。

**Comment by sugarspot** [comment]
クライアント側で度々チェックしてたら大変そうなので、基本的にサーバーにデータを問い合わせた際に存在しないユーザーIDからの問い合わせであれば、データ取得や登録・更新処理を受け付けないようにするのが手早いと思います
（サーバー側でなんらかのエラーを返すでも良いし、要求に応じて個別のエラー処理を行うでも良いと思います）

クライアントでもチェックするとしたら、起動時に１回だけユーザーIDでユーザー情報取得を行うくらいですかね

**Comment by yoship** [comment]
なるほどです。
了解しました。
前者ですねー。
