### ISSUE TITLE
[API]旧APIのregistration,user_detailsにsocial_id,social_typeを追加

### ISSUE THREAD

**Issue by sugarspot** [tamemap-old/tamemap-v2#74]
現在、アカウント生成時にsocial_typeを登録しているが、登録完了後のユーザー情報および、ユーザーの詳細情報取得時にsocial_typeが返却されていない

そのため、Facebook,Twitter,Email&Passwordのいずれでログインされているか判別ができないため、正しいログアウト処理が行えない

旧APIを修正するか、新規にユーザーの詳細を取得するAPIを作成するなど対応をお願いします

**Comment by kota777** [comment]
旧APIの方を修正しました
